[versions]
firebaseCrashlyticsGradle = "3.0.1"
fragment = "1.7.1"
androidxCore = "1.13.1"
androidxEspresso = "3.5.1"
androidxTest = "1.1.5"
appCompat = "1.6.1"
googleServices = "4.4.1"
gradle = "8.4.1"
kotlinGradlePlugin = "2.0.0"
lifecycle = "2.8.0"
constraintlayout = "2.1.4"
datastore = "1.1.1"
navigation = "2.7.7"
perfPlugin = "1.4.2"
preference = "1.2.1"
paging = "3.3.0"
palette = "1.0.0"
material = "1.12.0"
hiltdagger = "2.51.1"
dotsindicator = "5.0"
retrofit2 = "2.11.0"
logging-interceptor= "4.12.0"
coil = "2.6.0"
leakcanary = "3.0-alpha-6"
junit= "4.13.2"

[libraries]
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltdagger" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
perf-plugin = { module = "com.google.firebase:perf-plugin", version.ref = "perfPlugin" }
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
paging = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
palette = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
material= { module = "com.google.android.material:material", version.ref = "material" }
hiltdagger = { module = "com.google.dagger:hilt-android", version.ref = "hiltdagger" }
hiltdagger-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltdagger" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }

retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit2" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

deps_firebase_bom = "com.google.firebase:firebase-bom:33.0.0"
deps_firebase_crashlytics = { module  ="com.google.firebase:firebase-crashlytics-ktx" }
deps_firebase_analytics = { module  ="com.google.firebase:firebase-analytics-ktx" }
deps_firebase_perf = { module  ="com.google.firebase:firebase-perf-ktx" }

junit = { module = "junit:junit", version.ref = "junit" }
androidxTest = { module = "androidx.test.ext:junit", version.ref = "androidxTest" }
androidxEspresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }

